---
title: "RMT plots"
author: "sutton"
date: "11/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(ggrepel)
library(tidyverse)
library(readr)
library(dplyr)


#load data
catchcomp <- read.csv("Results/IN2020_V08_CatchComp.csv")
```
#Sutton modifications:
## use Acoustic_Category 
## use speed estiamted volume filtered

```{r AE code slightly modified}
#Sutton modifications:
# use Acoustic_Category 
# use speed estiamted volume filtered

#NO Gelatinous
distinct(catchcomp,Acoustic_Category) 

catchcomp_noG <- catchcomp %>% filter(Acoustic_Category== "Cephalopod"|Acoustic_Category== "Crustaceans"|Acoustic_Category== "F"|Acoustic_Category== "FGB"|
                                        Acoustic_Category== "FnGB"| Acoustic_Category== "other")

distinct(catchcomp_noG,Acoustic_Category)

day_values_noG <- catchcomp_noG %>% 
  filter(daylight== "Day")

night_values_noG <- catchcomp_noG %>% 
  filter(daylight== "Night")
night_values_noG <- night_values_noG %>%
  mutate_if(is.numeric, funs(. * -1))

catchcomp_plot_noG <- ggplot(catchcomp_noG, aes(x= Weight_Std_gm3_sp, y= Depth_Stratum, fill= Taxa_PLAOS))  +
  geom_rect(xmax= -Inf, xmin= 0, ymin=-Inf, ymax=Inf, fill= "lightgray", alpha= 0.7) +
  geom_bar(data= day_values_noG, stat= "identity")+ geom_bar(data= night_values_noG, stat= "identity") +
  theme_bw()  + facet_wrap(~Site) + labs(y="Depth Stratum", x="Biomass") +
  facet_grid(rows= vars(Site), cols= vars(Acoustic_Category), scales = "fixed") + geom_vline(xintercept= 0) 

plot(catchcomp_plot_noG)
ggsave("figures/catchcomp_noG.jpg")
```
#plot just Gelatinous
```{r Gelatinous }
catchcomp_G <- catchcomp %>% filter(Taxa_PLAOS== "Chaetognath" | Taxa_PLAOS== "Ctenophore" | Taxa_PLAOS== "Medusa"| Taxa_PLAOS== "Pyrosome"| Taxa_PLAOS== "Salp"
                                    | Taxa_PLAOS== "Siph_physonect"| Taxa_PLAOS== "Siphohonphore")

day_values_G <- catchcomp_G %>% 
  filter(daylight== "Day")

night_values_G <- catchcomp_G %>% 
  filter(daylight== "Night")
night_values_G <- night_values_G %>%
  mutate_if(is.numeric, funs(. * -1))

catchcomp_plot_G <- ggplot(catchcomp_G, aes(x= Weight_Std_gm3_sp, y= Depth_Stratum, fill= Taxa_PLAOS))  +
  geom_rect(xmax= -Inf, xmin= 0, ymin=-Inf, ymax=Inf, fill= "lightgray", alpha= 0.7) +
  geom_bar(data= day_values_G, stat= "identity")+ geom_bar(data= night_values_G, stat= "identity") +
  theme_bw()  + facet_wrap(~Site) + labs(y="Depth Stratum", x="Biomass") +
  facet_grid(rows= vars(Site), cols= vars(Acoustic_Category), scales = "fixed") + geom_vline(xintercept= 0) 

plot(catchcomp_plot_G)
ggsave("figures/catchcomp_G.jpg")


# filter(!Taxa_PLAOS== "Chaetognath" | !Taxa_PLAOS== "Ctenophore" | !Taxa_PLAOS== "Medusa"| !Taxa_PLAOS== "Pyrosome"| !Taxa_PLAOS== "Salp"
# | !Taxa_PLAOS== "Siph_physonect"| !Taxa_PLAOS== "Siphohonphore")
# facet_wrap(~Species_facet, scales = "free")

ggsave(catchcomp_plot, filename = "RMTplot.jpg")
# coord_cartesian(xlim= c(-0.1, 0.1))
# scale_fill_manual(values = cbp1) +

```


```{r catch comp}
colnames(catchcomp)
catchcomp <- catchcomp %>%
  filter(Depth_Stratum== "Epi" | Depth_Stratum== "Meso" | Depth_Stratum== "Lmeso") %>%
  mutate(weight_1000gm3 = 1000*Weight_Std_gm3_sp)
 
catchcomp$Depth_Stratum <- factor(as.factor(catchcomp$Depth_Stratum), levels=c("Lmeso","Meso","Epi"))

```

## create day night grouping
```{r day and night}

day_values <- catchcomp %>% 
  filter(daylight== "Day")

night_values <- catchcomp %>% 
  filter(daylight== "Night")
night_values <- night_values %>%
  mutate_if(is.numeric, funs(. * -1))
```

```{r rmt  plots}
#library(rcartocolor)
# bold <- carto_pal("Bold", n= 15)
# bold
# cbp1 <- c("#7F3C8D", "#11A579", "#3969AC", "#F2B701", "#E73F74", "#80BA5A","#E68310", "#008695", "#CF1C90", "#A5AA99" )

distinct(catchcomp,Site)

catchcomp_plot <- ggplot(catchcomp, aes(x= Weight_Std_gm3_gps, y= Depth_Stratum, fill= Taxa_PLAOS))  +
  geom_rect(xmax= -7, xmin= 0, ymin=-Inf, ymax=Inf, fill= "lightgray", alpha= 0.7) +
  geom_bar(data= day_values, stat= "identity")+ geom_bar(data= night_values, stat= "identity") +
  theme_classic()  + facet_wrap(~Site) + labs(y="Depth Stratum", x="Biomass") +
  facet_wrap(~Species_facet, scales = "free") + geom_vline(xintercept= 0) 
#plot(catchcomp_plot)
# coord_cartesian(xlim= c(-0.1, 0.1))
# scale_fill_manual(values = cbp1) +

catchcomp_plot_1 <- ggplot(catchcomp, aes(x= Weight_Std_gm3_gps, y= Depth_Stratum, fill= Taxa_PLAOS))  +
  geom_rect(xmax= -7, xmin= 0, ymin=-Inf, ymax=Inf, fill= "lightgray", alpha= 0.7) +
  geom_bar(data= day_values, stat= "identity")+ geom_bar(data= night_values, stat= "identity") +
  theme_classic()  + facet_wrap(~Site) + labs(y="Depth Stratum", x="Biomass") +
  facet_wrap(~Acoustic_Category, scales = "free") + geom_vline(xintercept= 0) 
#plot(catchcomp_plot_1)
# coord_cartesian(xlim= c(-0.1, 0.1))
# scale_fill_manual(values = cbp1) +

#SOTS
catchcomp_plot_SOTS <- ggplot(filter(catchcomp,Site =="SOTS"), 
                         aes(x= weight_1000gm3, 
                             y= Depth_Stratum, fill= Taxa_PLAOS))  +
  geom_rect(xmax= -7, xmin= 0, ymin=-Inf, ymax=Inf, fill= "lightgray", alpha= 0.7) +
  geom_bar(data= filter(day_values,Site == "SOTS"),stat= "identity") + 
  geom_bar(data= filter(night_values,Site == "SOTS"), stat= "identity") +
  theme_classic() + 
  labs(y="Depth Stratum", x="SOTS Biomass") +
  facet_wrap(~Acoustic_Category, scales = "free") + 
  geom_vline(xintercept= 0)
plot(catchcomp_plot_SOTS)

#55S
catchcomp_plot_55S <- ggplot(filter(catchcomp,Site =="55S"), 
                         aes(x= weight_1000gm3, 
                             y= Depth_Stratum, fill= Taxa_PLAOS))  +
  geom_rect(xmax= -7, xmin= 0, ymin=-Inf, ymax=Inf, fill= "lightgray", alpha= 0.7) +
  geom_bar(data= filter(day_values,Site == "55S"),stat= "identity") + 
  geom_bar(data= filter(night_values,Site == "55S"), stat= "identity") +
  theme_classic() + 
  labs(y="Depth Stratum", x="55S Biomass") +
  facet_wrap(~Acoustic_Category, scales = "free") + 
  geom_vline(xintercept= 0)
plot(catchcomp_plot_55S)

#58S
catchcomp_plot_58S <- ggplot(filter(catchcomp,Site =="58S"), 
                         aes(x= weight_1000gm3, 
                             y= Depth_Stratum, fill= Taxa_PLAOS))  +
  geom_rect(xmax= -7, xmin= 0, ymin=-Inf, ymax=Inf, fill= "lightgray", alpha= 0.7) +
  geom_bar(data= filter(day_values,Site == "58S"),stat= "identity") + 
  geom_bar(data= filter(night_values,Site == "58S"), stat= "identity") +
  theme_classic() + 
  labs(y="Depth Stratum", x="58S Biomass") +
  facet_wrap(~Acoustic_Category, scales = "free") + 
  geom_vline(xintercept= 0)
plot(catchcomp_plot_58S)
```